### PR TITLE
Merge route and prefix attributes

### PR DESCRIPTION
**Pull request by ton31337**
Merge prefix and route attributes, because it's absolutely not necessary to have both. It's more understandable to have one attribute like route/prefix instead of two.

### CODE REVIEW

**Comment by martinisoft** [comment]
Hi @ton31337 

Can you catch this branch up to current master? I can see about merging this before release as well.

**Comment by ton31337** [comment]
Just a moment.

On Wed, Jun 17, 2015 at 9:13 PM, Aaron Kalin <notifications@github.com>
wrote:

> Hi @ton31337 <https://github.com/ton31337>
>
> Can you catch this branch up to current master? I can see about merging
> this before release as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aetrion/exabgp-cookbook/pull/5#issuecomment-112900509>
> .
>



-- 
Donatas

**Comment by ton31337** [comment]
Done.

**Comment by martinisoft** [comment]
Sweet, thank you @ton31337! Will merge and make sure you are in the change log. :heart:

**Pull request merged**
