### PR TITLE
Add distribution packages

### PR DESCRIPTION
**Pull request by jmauro**
Hello,

This PR is link to https://github.com/dnsimple/chef-exabgp/issues/15

Let me know @martinisoft or @onlyhavecans if this is the spirit of the cookbook.

Regards,
JM

### CODE REVIEW

**Review by martinisoft — CHANGES_REQUESTED** [review]
I'd like to see a test case via Inspec for this install type if you can. Can just make a new recipe file in the test cookbook and add a suite to verify this.

**Comment by jmauro** [comment]
Hello @martinisoft, kitchen suite added for "package"

**Comment by jmauro** [comment]
Ping @martinisoft?

**Review by martinisoft — APPROVED** [review]

**Comment by martinisoft** [comment]
Thank you for making those corrections and for your contribution ❤️ . Barring any objections from @onlyhavecans I think we can merge and :shipit: this week.

**Review by onlyhavecans — APPROVED** [review]
👍

**Comment by jmauro** [comment]
Hello, 

Ping for this PR?

**Comment by martinisoft** [comment]
Hi @jmauro I'll promise to get this merged and shipped in the next couple of days (adding it to my work board now). Apologies for not getting to it before.

**Pull request merged**
